on: [push, pull_request]
name: Test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
        with:
          go-version: 1.x

      - name: fmt
        run: test -z $(gofmt -l .)

      - name: vet
        run: go vet ./...

      - name: staticcheck
        uses: dominikh/staticcheck-action@288b4e28bae83c59f35f73651aeb5cab746a06fc  # v1.4.0
        with:
          install-go: false

  test:
    strategy:
      matrix:
        go-version: [1.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Test
        run: go test -race ./...
